version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: personality-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./Backend/questions:/app/questions:ro
      - ./Backend/norms:/app/norms:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./Frontend
    container_name: personality-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api

networks:
  default:
    name: personality-network