version: '3.8'

services:
  backend-pip:
    build: ./BackendPip
    container_name: personality-backend-pip
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./BackendPip/questions:/app/questions:ro
      - ./BackendPip/norms:/app/norms:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./Backend
    container_name: personality-backend-node
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - PORT=8001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_PIP_URL=http://backend-pip:8000
    depends_on:
      - backend-pip
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./Frontend
    container_name: personality-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - backend-pip
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_AUTH_API_URL=http://localhost:8001/api
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

networks:
  default:
    name: personality-network